In [2]:
import numpy as np

In [7]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
print(a[0])

[1 2 3 4]


In [9]:
print(a[1])

[5 6 7 8]


In [11]:
print(a[2])

[ 9 10 11 12]


# Membuat Array

In [ ]:
np.array()
np.zeros()
np.ones()
np.empty()
np.arange()

In [12]:
a = np.array([1, 2, 3])

In [13]:
a

array([1, 2, 3])

In [14]:
# you can easily create an array filled with 0s
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
# Or an array filled with 1s
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [19]:
# Or even an empty array!
# The function empty creates an array whose initial content is random and depends on the state of the memory.

print(np.empty(6))

[1. 1. 1. 1. 1. 1.]


In [17]:
# You can create an array with a range of elements

print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [20]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [ ]:
np.append()
np.delete()
np.sort()

In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [23]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [24]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [25]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
ndarray.ndim()
ndarray.size()
ndarray.shape()

In [27]:
array_example = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]], [[0, 1, 2, 3], [4, 5, 6, 7]], [[0, 1, 2, 3], [4, 5, 6, 7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [28]:
array_example.ndim

3

In [29]:
array_example.size

24

In [30]:
array_example.shape

(3, 2, 4)

In [31]:
arr_one = np.array([[1,2,3,4,5]])

In [33]:
arr_one

array([[1, 2, 3, 4, 5]])

In [32]:
arr_one.ndim

2

In [34]:
arr_one.size

5

In [35]:
arr_one.shape

(1, 5)

In [39]:
np.reshape()

<function numpy.reshape(a, newshape, order='C')>

In [41]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [42]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [43]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Convert 1D to 2D

In [45]:
np.newaxis
np.expand_dims

<function numpy.expand_dims(a, axis)>

In [46]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [47]:
# You can use np.newaxis to add new axis:

a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [48]:
# You can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [49]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [50]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [51]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

# Indexing and Slicing

In [53]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [54]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
# You can easily print all of the values in the array that are less than 5

print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]


In [56]:
five_up = (a >= 5)

print(a[five_up])
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [57]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [58]:
# You can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


# Membuat Array dari Data yang Ada

In [ ]:
slicing indexing
np.vstack()
np.hstack()
np.hsplit()
.view()
.copy()

In [60]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [61]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [64]:
a_1 = np.array([[1,1], [2,2]])
a_2 = np.array([[3,3], [4,4]])

In [65]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [66]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# TipsPy Day 4

In [5]:
a = np.random.rand(5)
a

array([0.93619064, 0.1772263 , 0.06636995, 0.59004076, 0.84428794])

In [6]:
a.shape

(5,)

In [7]:
a.T

array([0.93619064, 0.1772263 , 0.06636995, 0.59004076, 0.84428794])

In [8]:
np.dot(a, a.T)

1.9732372677506136

In [10]:
a = np.random.rand(5,1) # column vector
a

array([[0.84808734],
       [0.74192106],
       [0.97441943],
       [0.74267741],
       [0.78234259]])

In [11]:
a.T

array([[0.84808734, 0.74192106, 0.97441943, 0.74267741, 0.78234259]])

In [12]:
np.dot(a, a.T)

array([[0.71925214, 0.62921386, 0.82639279, 0.62985531, 0.66349485],
       [0.62921386, 0.55044686, 0.7229423 , 0.55100801, 0.58043645],
       [0.82639279, 0.7229423 , 0.94949323, 0.7236793 , 0.76232982],
       [0.62985531, 0.55100801, 0.7236793 , 0.55156973, 0.58102817],
       [0.66349485, 0.58043645, 0.76232982, 0.58102817, 0.61205993]])

In [14]:
a = np.random.rand(1,5) # row vector
a

array([[0.44394548, 0.05149455, 0.80667365, 0.32196565, 0.00708021]])