# CHAPTER 3
# NumPy Workshop
Disini kita akan belajar tentang NumPy

In [2]:
import numpy as np
np.__version__

'1.21.5'

## Python List

Misalkan kita menyimpan IPK seorang mahasiswa disetiap semester. Mahasiswa ini telah menyelesaikan 3 semester. Berikut IPK seorang mahasiswa:
- Semester 1 = 4.0
- Semester 2 = 3.2
- Semester 3 = 3.5

In [42]:
gpas_as_list = [4.0, 3.2, 3.5]

Inputan diatas tidak memunculkan output karena hanya mendefinisikan Array/List.

Ketika mahasiswa telah menyelesaikan semester 4. Kita akan menambahkan IPK Semester 4 yaitu 4.0

Gunakan method "append" untuk menambahkan di akhir list.
Jalankan "gpas_as_list" untuk melihat keseluruhan IPK.

In [43]:
gpas_as_list.append(4.0)
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

Ketika kita ingin menambahkan semester baru yang belum ada IPKnya.

Bedanya penggunaan method "Insert" dan "Append" yaitu :
- Append hanya bisa digunakan di akhir list, sedangkan Insert bisa digunakan di tengah list.

In [44]:
gpas_as_list.insert(1, "belum ada")
gpas_as_list

[4.0, 'belum ada', 3.2, 3.5, 4.0]

Method "pop" itu kebalikan dari "push", "append", dan "insert". Method "pop" akan mengambil dan menghapus data tersebut.

In [45]:
gpas_as_list.pop(1)
gpas_as_list

[4.0, 3.2, 3.5, 4.0]

## NumPy Array

Karena di awal kita sudah melakukan "import NumPy as np" jadi disini kita hanya menggunakan np. Method "Array" bisa digunakan untuk memakai data sebelumnya dengan mengconvert dari list python menjadi array.

In [22]:
gpas = np.array(gpas_as_list)

Jalankan dengan method dtype untuk mengetahui tipe data apa.

In [23]:
gpas.dtype

dtype('<U32')

Jalankan dengan method size untuk mengetahui jumlah atau sizenya.

In [46]:
gpas.size

4

# cheat sheet

- append = menambahkan di akhir list

- insert = menambahkan di tengah list

- pop = menghapus data

- array

- dtype = cek tipe data

- size = cek jumlah data

# Demo Aplikasi Study Log dengan Array
Study Log ini adalah aplikasi untuk mencatat berapa lama kita belajar setiap harinya selama 100 hari kedepan. Aplikasi ini sangat cocok menggunakan NumPy Array. Karena jumlahnya sudah pasti 100 data.

Mengubah tipe data float menjadi uint16 agar sizenya lebih kecil atau menghemat penggunaan memori di Python.

In [7]:
study_minutes = np.zeros(100, np.uint16)
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

Dengan menjalankan sintaks %whos kita dapat melihat statistik variabel-variabel yang sudah didefinisikan oleh Jupyter Notebook yang saat ini kita buka.

In [8]:
%whos

Variable        Type       Data/Info
------------------------------------
np              module     <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>
os              module     <module 'os' from 'c:\\anaconda\\lib\\os.py'>
study_minutes   ndarray    100: 100 elems, type `uint16`, 200 bytes
sys             module     <module 'sys' (built-in)>


# Array Multidimensi

In [3]:
students_gpas = np.array([
    [4.0, 3.3, 3.5, 4.0],
    [3.96, 3.92, 4.0, 4.0],
    [3.2, 3.8, 4.0, 4.0]
], np.float16)
students_gpas

array([[4.  , 3.3 , 3.5 , 4.  ],
       [3.96, 3.92, 4.  , 4.  ],
       [3.2 , 3.8 , 4.  , 4.  ]], dtype=float16)

In [6]:
students_gpas.ndim

2

In [7]:
students_gpas.shape

(3, 4)

In [8]:
students_gpas[2]

array([3.2, 3.8, 4. , 4. ], dtype=float16)

In [10]:
students_gpas[2][3]

4.0