# CHAPTER 4
Tentang manipulasi dan organisasi array.

## Lesson 1 : Array Indexing
Cara penggunaan Array Indexing menggunakan NumPy

In [2]:
import numpy as np
np.__version__

'1.21.5'

### DEMO : Study Log MultiDimensi dengan NumPy

Kita mulai dengan membuat Array bernama study_minutes. Sebelumnya kita sudah membuat study_minutes yang isinya 0 semua.

In [42]:
study_minutes = np.zeros(100, np.uint16)

In [43]:
study_minutes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint16)

Kita akan convert study_minutes awal yaitu dari Array 1 Dimensi menjadi Array 2 Dimensi. Kemudian kita isi angkanya sejumlah 100 dengan 2 dimensi.

In [44]:
study_minutes = np.array([
    study_minutes,
    np.zeros(100, np.uint16)
])

### Method Shape
Kemudian kita cetak ukuran dimensinya dengan method shape.

In [45]:
study_minutes.shape

(2, 100)

Study log atau study_minutes memiliki 2 dimensi. Tiap log memiliki 2 ronde. Tiap data memiliki ronde seperti ronde 1, ronde 2, hari pertama, hari kedua, dan seterusnya.

Misal kita punya data baru, hari ke-1 ronde kedua kita belajar 60 menit.

In [35]:
study_minutes[1][0] = 60
study_minutes

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [60,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0]], dtype=uint16)

Jika kita ingin aplikasi terlihat real jadi tidak 0 semua isinya. Kita bisa menggunakan method RandomState untuk mengisi nilai random.

Pertama-tama kita buat log baru yaitu fake.log. Jadi kita isi angka minimum 30 dan maksimum 180. Sizenya sebanyak 100 dan tipe data integer. Kemudian kita print fake_log.

### Method RandomState

In [4]:
rand = np.random.RandomState(46)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([ 99,  45,  70, 162, 146,  70, 177, 176,  47, 148, 123,  67,  90,
       122,  34, 160, 135, 102,  62,  61,  85,  52, 153, 128,  89,  37,
       109,  60, 128,  57, 160,  67, 144,  97, 150, 148,  32, 155, 116,
       137,  49,  70, 159, 159,  84, 114,  93, 110,  81, 122, 103,  53,
        52, 147,  75,  93,  45,  46, 177,  91,  70,  69,  46, 150,  86,
       170, 174, 143,  88,  71, 132,  67, 157, 118,  91, 158, 178, 176,
        37, 155,  45,  66,  60,  35, 154,  75,  53,  33,  80, 126,  76,
       113, 148, 163,  57,  83, 145, 148, 167, 129], dtype=uint16)

Jika kita ingin memiliki sebuah Array yang isinya adalah menit yang nyaris mencapai 60 menit, contohnya di indeks ke-1 ada 45 menit dan indeks ke-21 ada 52 menit. Kita cari yang terdekat saja.

Cara manual bisa kita akses seperti ini:

1. Cara Pertama

In [37]:
fake_log[1], fake_log[21]

(45, 52)

2. Cara Kedua :

In [38]:
fake_log[[1, 21]]

array([45, 52], dtype=uint16)

Dari 2 cara diatas, menghasilkan hasil yang sama. Bedanya cara pertama menjadi List, sedangkan cara kedua menjadi Array. 

Jika kita ingin membuat Array baru berdasarkan indeks-indeks tadi. Pertama kita buat variabel baru bernama index. Lalu kita konstruksikan sebuah Array baru yang isinya [1, 21] dan [1, 2].

Selanjutnya kita filter fake_log dengan menggunakan index.
### Array Baru

In [39]:
index = np.array([
    [1, 21],
    [1, 2]
])
fake_log[index]

array([[45, 52],
       [45, 70]], dtype=uint16)

### Method Append
Jika kita ingin membuat ronde baru yaitu ronde ke-3.

In [40]:
study_minutes = np.append(study_minutes, [fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  60,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

# Lesson 3 : Slicing Array 

### Method Arange

In [5]:
 practice = np.arange (42)
 practice.shape = (7, 6)
 practice

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [14]:
practice[2, 1]

13

In [13]:
practice[2:5]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [15]:
practice[2:5, 3]

array([15, 21, 27])

In [16]:
practice[2:5, 3:]

array([[15, 16, 17],
       [21, 22, 23],
       [27, 28, 29]])

# Lesson 4 : Copy vs View

In [23]:
practice_list = [1, 2, 3]
practice_list_copy = practice_list[:]
practice_list, practice_list_copy
practice_list_copy[0] = 12345
practice_list, practice_list_copy

([1, 2, 3], [12345, 2, 3])

In [27]:
not_copied = practice[:]
not_copied[0, 0] = 12345
practice, not_copied

(array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]),
 array([[12345,     1,     2,     3,     4,     5],
        [    6,     7,     8,     9,    10,    11],
        [   12,    13,    14,    15,    16,    17],
        [   18,    19,    20,    21,    22,    23],
        [   24,    25,    26,    27,    28,    29],
        [   30,    31,    32,    33,    34,    35],
        [   36,    37,    38,    39,    40,    41]]))

In [28]:
print(practice.base)

None


In [29]:
print(not_copied.base)

[[12345     1     2     3     4     5]
 [    6     7     8     9    10    11]
 [   12    13    14    15    16    17]
 [   18    19    20    21    22    23]
 [   24    25    26    27    28    29]
 [   30    31    32    33    34    35]
 [   36    37    38    39    40    41]]


In [30]:
not_copied.base is practice

True

In [31]:
not_copied.base is practice_list

False

terakhir 52:00

#  Lesson 2 : Filter Array

### DEMO : Filter Array Menggunakan NumPy dengan Kondisi
Mencari durasi belajar dibawah 1 jam (60 menit)

Jika ingin mencari daftar nilai yang mendekati 60 menit atau 1 jam menggunakan cara NumPy Array :

TRUE = dibawah 60 menit, dan FALSE = diatas 60 menit

In [5]:
fake_log < 60

array([False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False,  True,  True, False,
       False, False,  True,  True, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False, False,  True, False, False,  True,  True, False, False,
       False, False, False, False,  True, False, False, False, False,
       False])

Jika kita ingin menggunakan data ini untuk menciptakan sebuah Array baru yang isinya hanyalah nilai yang dibawah 60 menit caranya dengan memfilter fake_log < 60 seperti ini:

In [6]:
fake_log[fake_log < 60]

array([45, 47, 34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53,
       33, 57], dtype=uint16)

Bandingkan dengan cara iteratif dengan cara Python for loop. Diawali dengan membuat list kosong results. Dibaca {Untuk value di fake_log, Jika value kurang dari 60 maka tambahkan ke list results}. Kemudian cetak kembali NumPy array "np.array(result)".

In [7]:
results = []
for value in fake_log:
    if value < 60:
        results.append(value)

np.array(results)

array([45, 47, 34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53,
       33, 57], dtype=uint16)

Jika kita ingin memfilter study_minutes dengan nilai dibawah 60 menit.

In [8]:

study_minutes = np.zeros(100, np.uint16)
study_minutes = np.append(study_minutes, [fake_log])
study_minutes

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,  99,  45,  70, 162,
       146,  70, 177, 176,  47, 148, 123,  67,  90, 122,  34, 160, 135,
       102,  62,  61,  85,  52, 153, 128,  89,  37, 109,  60, 128,  57,
       160,  67, 144,  97, 150, 148,  32, 155, 116, 137,  49,  70, 159,
       159,  84, 114,  93, 110,  81, 122, 103,  53,  52, 147,  75,  93,
        45,  46, 177,  91,  70,  69,  46, 150,  86, 170, 174, 143,  88,
        71, 132,  67, 157, 118,  91, 158, 178, 176,  37, 155,  4

In [9]:
study_minutes[study_minutes < 60]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 45, 47,
       34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53, 33, 57],
      dtype=uint16)

Jika kita ingin menghilangkan nilai 0. Jadi kita memfilter durasi lebih dari 0 menit dan kurang dari 60 menit seperti berikut :

In [10]:
study_minutes[(study_minutes < 60) & (study_minutes > 0)]

array([45, 47, 34, 52, 37, 57, 32, 49, 53, 52, 45, 46, 46, 37, 45, 35, 53,
       33, 57], dtype=uint16)

Kita bisa menciptakan Array yang isinya boolean dengan kondisi fake_log < 60. Boolean Array ini juga dapat menggunakan Operator Bitwise AND (&) dan OR (|). Jadi kita tidak memakai sintaks AND dan OR seperti Python. Kita bisa menyiptakan Array baru, Array Boolean seperti fake_log[fake_log < 60]