# CHAPTER 5
Di Aljabar Linear ini kita akan belajar cara pemrograman yang sedikit berbeda dalam pemrograman pada umumnya kita akan melakukan pemrograman berbasis Array atau bisa disebut dengan Array Programming. Di Array Programming ini kita tidak akan melakukan manipulasi data dengan Looping melainkan menggunakan berbagai operasi kedalam Array secara keseluruhan.

Seperti yang telah kita pelajari di lesson sebelumnya bagaimana kita melakukan slicing filtering dan juga melihat perbedaan antara Python List dan NumPy Array dalam hal Copy dan View.

In [5]:
import numpy as np
np.__version__

'1.21.5'

# Lesson 1 : Aljabar Linear

Contoh kasus:
ketika saya menemukan nasi uduk yang sangat enak, lalu saya kabarin ke temen saya bahwa ada nasi uduk yang saya rekomendasikan dan mereka nitip untuk dibelikan nasi uduk dan berbagai sarapan lainnya. Awalnya seru tapi makin hari makin banyak pesanan yang saya terima sampai ada pesanan yang berbeda-beda. Ada yang pesan nasi uduk saja, ada yang ditambah gorengan, dan ada yang tambah kopi. Semakin banyak dan semakin bervariasi, semakin susah mencari tahu siapa yang pesan apa dan tagihannya pun berbeda-beda sehingga akan kesulitan untuk saya menagih ke temen-temen saya.

Nah masalah2 seperti ini bisa kita jabarkan dengan aljabar linear.
 

Diketahui :
2 Nasi 0 Gorengan 0 Kopi 0 Lontong = 20.000
1 Nasi 0 Gorengan 2 Kopi 4 Lontong = 32.000
1 Nasi 2 Gorengan 1 Kopi 0 Lontong = 20.000
4 Nasi 6 Gorengan 0 Kopi 2 Lontong = 61.000

In [18]:
orders = np.array([
    [2, 0, 0, 0],
    [1, 0, 2, 4],
    [1, 2, 1, 0],
    [4, 6, 0, 2]
])
totals = np.array([20000, 32000, 20000, 61000])
prices = np.linalg.solve(orders, totals)
prices

array([10000.,  2500.,  5000.,  3000.])

Jadi untuk harga Nasi 10000, Gorengan 2500, Kopi 5000, Lontong 3000.

Jika ingin mencari total harga sbb :

In [17]:
orders @ prices

array([20000., 32000., 20000., 61000.])

Jadi di NumPy ini kita bisa menggunakan module linalg / linear aljabar untuk menghitung nilai dari aljabar linear. Kita bisa menggunakan method solve untuk mengungkap misteri harga per item dari titipan sarapan temen-temen kita. Kita juga bisa menggunakan notasi at sign / akeong untuk mengalikan kedua array / matriks multification. Dalam hal ini Array of orders dan array of prices.

# Lesson 2 : Fungsi Universal

Kita akan membahas fungsi2 umum/ universal yang biasa kita gunakan untuk operasi matriks/ vektor. Jika kita bekerja dengan data yang jumlahnya besar/ matriks yang jumlahnya banyak pasti akan berhadapan dengan operasi matematika antar matriks seperti penjumlahan, pengurangan, perkalian, pembagian dan sebagainya.

Nah sebelum kita melihat contoh dan demonya, kita bahas dulu yang kita pelajari dari lesson sebelumnya. Pastinya kita sudah belajar tentang Aljabar Linear bagaimana Aljabar Linear yang kita gunakan untuk solving problem keseharian kita.

Misalnya saya ingin punya 2 Array yang akan kita operasi matematika.

In [20]:
a, b = np.split(np.arange(1, 11), 2)
a, b

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [21]:
a + b

array([ 7,  9, 11, 13, 15])

In [22]:
a * b

array([ 6, 14, 24, 36, 50])

In [23]:
a - b

array([-5, -5, -5, -5, -5])

In [24]:
a / b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [28]:
a - b

array([-5, -5, -5, -5, -5])

In [27]:
b - a

array([5, 5, 5, 5, 5])

In [29]:
a + 3

array([4, 5, 6, 7, 8])

In [30]:
a + np.repeat(3, 5)

array([4, 5, 6, 7, 8])

Operasi-operasi ini di NumPy biasa disebut Universal Function.
http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs

In [31]:
x1 = np.arange(9.0).reshape((3,3))
x2 = np.arange(3.0)
x1, x2

(array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]),
 array([0., 1., 2.]))

In [32]:
np.add(x1, x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [33]:
np.add(x1, 2)

array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]])

Jadi kita tidak perlu melakukan Looping untuk operasi matematika lainnya. Operasi matematika umum seperti tambah/kali/kurang/bagi sudah divektorasi sehingga dapat digunakan untuk operasi matriks yang sifatnya 1 dimensi ataupun multidimensi.

# Lesson 3 : Operasi Matriks Lainnya

Kita akan membahas beberapa operasi matriks yang menarik yang bisa kita gunakan. Setelah sebelumnya kita mempelajari fungsi universal seperti kurang/bagi/kali/tambah dll.

Nah ada banyak fungsi statistik di NumPy yang bisa kita gunakan seperti average, 

In [10]:
study_minutes = np.zeros(100, np.uint16)
rand = np.random.RandomState(46)
fake_log = rand.randint(30, 180, size=100, dtype=np.uint16)
fake_log

array([ 99,  45,  70, 162, 146,  70, 177, 176,  47, 148, 123,  67,  90,
       122,  34, 160, 135, 102,  62,  61,  85,  52, 153, 128,  89,  37,
       109,  60, 128,  57, 160,  67, 144,  97, 150, 148,  32, 155, 116,
       137,  49,  70, 159, 159,  84, 114,  93, 110,  81, 122, 103,  53,
        52, 147,  75,  93,  45,  46, 177,  91,  70,  69,  46, 150,  86,
       170, 174, 143,  88,  71, 132,  67, 157, 118,  91, 158, 178, 176,
        37, 155,  45,  66,  60,  35, 154,  75,  53,  33,  80, 126,  76,
       113, 148, 163,  57,  83, 145, 148, 167, 129], dtype=uint16)

In [44]:
study_minutes = np.append(study_minutes, [fake_log])

In [48]:
study_less = study_minutes[(study_minutes < 60) & (study_minutes > 0)]
print(study_less)
np.add.reduce(study_less)

[45 47 34 52 37 57 32 49 53 52 45 46 46 37 45 35 53 33 57]


855

In [53]:
np.sum(study_less)

855

In [54]:
np.sum(study_minutes)

10415

https://docs.spicy.org

Yang sudah kita pelajari di chapter 5 ini adalah apa itu aljabar linear dan bagaimana pengunaannya untuk memecahkan masalah-masalah yang kita temui. Kemudia kita juga sudah melihat beberapa fungsi universal yang bisa kita gunakan untuk melakukan operasi matematika antar matriks. Terakhir, beberapa operasi matriks lainnya juga sudah kita demokan.